# Chatter
# ---
# Модуль для показа радио-сообщений и субтитров прямой речи в обход стандартного
# systemChat, который часто ломается.
# Также предоставляет API для других модулей для отображения радио-переговоров.
#
# Зависимости:
# нет

Init:
    timeout: 1
    condition: { true }

# Настройки для радио-сообщений
Radio:
    # Коэффициент усиления помех с дистанцией
    # Например, для ДВ рации с дальностью 10км и коэф. 0.8 - помехи начинаются с 8км
    NoiseDistanceCoef: 0.8

    # Коэффициент статических помех на предельной дистанции
    # Например, для ДВ рации с дальностью 10км и коэф. 1.2 - сообщение будет приниматься,
    # но как статические помехи на дистанции 10-12км.
    StaticsDistanceCoef: 1.2

    # Дальность рации по умолчанию, в метрах
    LR Range: 25000
    SW Range: 3000


# Настройки для прямой речи
Direct:
    # Коэффициент ухудшения "слышимости"
    # Например, с коэф. 0.75 для обычной речи (30м) часть слов будет не расслышать с 22,5м (0.75 * 30)
    NoiseDistanceCoef: 0.75

    # Дальность "слышимости" прямой речи (нормальная, шепот, крик)
    Say Range: 25
    Whisper Range: 7
    Shout Range: 75

# Описание "говорунов"
Talkers:
    # Пример:
    # - callsign: "PAPA BEAR" # Отображаемое имя
    #   unit: `papabear` # (Опционально) Имя юнита представляющего говоруна в миссии
    #                    # Если указан - дальность передачи/речи будет учитываться от позиции юнита
    #                    # Может быть GameLogic, тогда дистанция будет учитываться только для радио-сообщений
    #   LR: 50000 # (Опционально) Дальность передачи по ДВ, в метрах.
    #   SW: 1500 # (Опционально) Дальность передачи по КВ, в метрах.

    - callsign: "PAPA BEAR"
      unit: `papabear`
      LR: 1000
      SW: 500
